services:
  - type: web
    name: save-cuba-backend
    env: python
    region: ohio # O la región de Render que prefieras (ej. oregon, frankfurt)
    plan: free # Cambia a un plan de pago si necesitas más recursos o procesamiento pesado de PDF
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
